### ISSUE TITLE
The default Firebase app has not yet been configured

### ISSUE THREAD

**Issue by thaoula** [jhomlala/catcher#103]
Hi @jhomlala,

Thanks for your library. 

When upgrading to the last version with the integrated Firebase Crashalyitics. We get the following error -

`2020-07-22 14:21:48.475071+0700 Runner[2744:1239750] 6.28.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. `

Downgrading to version 0.3.14 fixes the error.

We do not plan on configuring firebase for our application. Do you know of a work around for this error?

Regards,
Tarek

**Comment by vrossini** [comment]
Same here :)

**Comment by jhomlala** [comment]
Fixed in 0.3.16. If anyone is still interested in using crashlytics, then here is example: https://github.com/jhomlala/catcher/blob/master/example/lib/crashlytics_example.dart

**Comment by mikeesouth** [comment]
@jhomlala did you revert crashlytics because of this swift error? Why not fixing it instead? I'd prefer to have an "official" crashlytics handler than to implement it myself using custom reports. That being said - I have a custom implementation that is working today but still, alot of third party handlers are supported so why not crashlytics?
