### ISSUE TITLE
Use of catcher's error widget generates 2 error widgets

### ISSUE THREAD

**Issue by bambinoua** [jhomlala/catcher#127]
I've implemented `builder` property for `MaterialApp` to replace default Flutter *red screen* with catcher's error widget. Then I emulate error situation. Then PageReportMode's widget is appeared and after that it is covered by error widget. Also if I generate `FlutterError` for example in `initState` I see red screen as usually and then it covered with catcher's error widget.

Is it correct situation? I thought the red scree will be replaced with error widget?

**Comment by jhomlala** [comment]
Some errors can't be caught by Catcher, since Flutter framework catches "too much" (for example error in initState). Catcher just overrides red screen of death where it possible, but for some reason Flutter framework don't use it sometimes. There's nothing I can do right now (there are some issues reported in Flutter github project, which wasn't yet handled).
