### ISSUE TITLE
Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.

### ISSUE THREAD

**Issue by HumbleCarl** [jhomlala/catcher#59]
How to fix this? I got this message logs Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.

**Comment by jhomlala** [comment]
https://github.com/jhomlala/catcher#adding-navigator-key

**Comment by visual-velocity** [comment]
I'm facing this issue, i already test with custom navigator key and Catcher navigator key, Report will not generate.
Catcher | FINE] Using debug config
Catcher | FINE] Catcher configured successfully.
Setup localization lazily!
Catcher | WARNING] Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.
ERROR: Não foi possivem oter informações da KEY

I used auto_route package inside my app. Can you suggest me why is this happening and showing this warning.

**Comment by Mufaddal1125** [comment]
I have the same issue.
I am using this with sentry SDK does it cause any problem?
